// A golden file, produced by the Go implementation itself.
//
// tests/workflowActivation.test.ts asserts the behaviour we *believe* the CLI
// has. This one asserts what it actually does: the fixture was generated by
// calling agent.WorkflowActivationSpans on each string and dumping the span
// offsets. If a pattern in internal/agent/workflow.go changes and the port
// does not, this fails — which is the only way to notice, because both sides
// keep working perfectly on their own while disagreeing about what a user
// asked for.
//
// To regenerate, in the spettro checkout:
//
//   1. add a test that writes json.Marshal of
//      map[string][][2]int{ <each case>: WorkflowActivationSpans(case) }
//   2. copy the output over tests/go-activation-spans.json here
//
// Add cases to the fixture rather than only here: a case this file knows about
// but the Go side was never asked about proves nothing.

import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { workflowActivationSpans } from '@shared/workflowActivation'

const GOLDEN: Record<string, [number, number][] | null> = JSON.parse(
  readFileSync(join(__dirname, 'go-activation-spans.json'), 'utf8')
)

describe('the port agrees with the Go implementation', () => {
  const cases = Object.entries(GOLDEN)

  it('has a fixture to check against', () => {
    expect(cases.length).toBeGreaterThan(20)
  })

  for (const [text, spans] of cases) {
    it(`matches on ${JSON.stringify(text)}`, () => {
      const mine = workflowActivationSpans(text).map((s) => [s.start, s.end])
      // Go marshals an empty result as null; an empty array means the same
      // thing to a renderer and is what the TypeScript side returns.
      expect(mine).toEqual(spans ?? [])
    })
  }
})
