// GENERATED by tools/visual/fixtures-from-live.cjs — do not edit by hand.
//
// A real ACP session, replayed through the same upsert rules chatSession.ts
// uses. This is the scene that is allowed to contradict the hand-written
// fixtures: when it does, the hand-written ones are wrong.
//
// Source: live-workflow-fixed.jsonl

import type { Scene } from './fixtures'

export const LIVE_SCENE: Scene = {
  id: 'live',
  title: "Live — real workflow run (recorded)",
  note: 'Recorded from a real `spettro --acp` turn. Every field is exactly what the CLI put on the wire.',
  items: [
    {
      "kind": "tool",
      "tool": {
        "id": "call-1",
        "title": "workflow {\"name\": \"check-files\", \"save_as\": \"check-files\", \"script\": \"export const meta = {\\n name: 'check-files',\\n description:…",
        "status": "failed",
        "output": "error: workflow: no saved workflow named \"check-files\" (looked in /tmp/claude-1000/-home-carlo-Desktop-Spettro-Spettro-Desktop/febcdfcd-93e1-4a78-9149-1a475e52f0c7/scratchpad/liveproj/.spettro/workflows, /home/carlo/.spettro/workflows)",
        "diffs": [],
        "locations": [],
        "timestamp": 1700000000000,
        "kind": "think",
        "argsJSON": "{\"name\":\"check-files\",\"save_as\":\"check-files\",\"script\":\"export const meta = {\\n name: 'check-files',\\n description: 'Read contents of a.txt, b.txt, c.txt',\\n phases: [{ title: 'Read' }],\\n}\\n\\nphase('Read')\\n\\nconst result = await parallel([\\n () => agent('Read the file a.txt in the current working directory and report its contents exactly.', { label: 'read:a.txt', phase: 'Read' }),\\n () => agent('Read the file b.txt in the current working directory and report its contents exactly.', { label: 'read:b.txt', phase: 'Read' }),\\n () => agent('Read the file c.txt in the current working directory and report its contents exactly.', { label: 'read:c.txt', phase: 'Read' }),\\n])\\n\\nreturn result\\n\"}"
      }
    },
    {
      "kind": "tool",
      "tool": {
        "id": "call-2",
        "title": "workflow {\"save_as\": \"check-files\", \"script\": \"export const meta = {\\n name: 'check-files',\\n description: 'Read contents of a.tx…",
        "status": "completed",
        "output": "<workflow_result name=\"check-files\" run_id=\"wf_20260824132936_59ae80e3\">\n<summary>3 agents · 0 failed · 0 replayed from journal · 29203 tokens</summary>\n<phases>Read</phases>\n<returned>\n[\n  \"The file `a.txt` contains exactly one line:\\n\\n```\\nalpha\\n```\",\n  \"The contents of `b.txt` are:\\n\\n```\\nbeta\\n```\",\n  \"The file `c.txt` contains exactly one word:\\n\\n```\\ngamma\\n```\"\n]\n</returned>\n</workflow_result>\nScript: inline · transcript: /home/carlo/.spettro/sessions/session-2fe4867b-9b46671d/workflows/wf_20260824132936_59ae80e3\nTo resume after an edit, re-run with script_path and resume_from_r\n... (truncated)",
        "diffs": [],
        "locations": [],
        "timestamp": 1700000001000,
        "kind": "think",
        "argsJSON": "{\"save_as\":\"check-files\",\"script\":\"export const meta = {\\n name: 'check-files',\\n description: 'Read contents of a.txt, b.txt, c.txt',\\n phases: [{ title: 'Read' }],\\n}\\n\\nphase('Read')\\n\\nconst result = await parallel([\\n () => agent('Read the file a.txt in the current working directory and report its contents exactly.', { label: 'read:a.txt', phase: 'Read' }),\\n () => agent('Read the file b.txt in the current working directory and report its contents exactly.', { label: 'read:b.txt', phase: 'Read' }),\\n () => agent('Read the file c.txt in the current working directory and report its contents exactly.', { label: 'read:c.txt', phase: 'Read' }),\\n])\\n\\nreturn result\\n\"}"
      }
    },
    {
      "kind": "tool",
      "tool": {
        "id": "wf-3",
        "title": "workflow check-files",
        "status": "completed",
        "output": "3 agents · 0 failed · 0 replayed\n\nRead contents of a.txt, b.txt, c.txt\n\n▸ Read — 3/3 done\n    ✓ general-purpose#3  read:c.txt\n    ✓ general-purpose#1  read:a.txt\n    ✓ general-purpose#2  read:b.txt",
        "diffs": [],
        "locations": [],
        "timestamp": 1700000002000,
        "kind": "think",
        "argsJSON": "{\"description\":\"Read contents of a.txt, b.txt, c.txt\",\"origin\":\"inline\",\"phases\":[{\"detail\":\"\",\"title\":\"Read\"}],\"run_id\":\"wf_20260824132936_59ae80e3\",\"workflow\":\"check-files\"}"
      }
    },
    {
      "kind": "tool",
      "tool": {
        "id": "call-4",
        "title": "agent general-purpose#3: read:c.txt",
        "status": "completed",
        "output": "The file `c.txt` contains exactly one word:\n\n```\ngamma\n```",
        "diffs": [],
        "locations": [],
        "timestamp": 1700000003000,
        "kind": "think",
        "argsJSON": "{\"agent\":\"general-purpose#3\",\"cached\":false,\"index\":3,\"parent_agent_id\":\"plan\",\"phase\":\"Read\",\"run_id\":\"wf_20260824132936_59ae80e3\",\"task\":\"read:c.txt\",\"workflow\":\"check-files\"}"
      }
    },
    {
      "kind": "tool",
      "tool": {
        "id": "call-5",
        "title": "agent general-purpose#1: read:a.txt",
        "status": "completed",
        "output": "The file `a.txt` contains exactly one line:\n\n```\nalpha\n```",
        "diffs": [],
        "locations": [],
        "timestamp": 1700000004000,
        "kind": "think",
        "argsJSON": "{\"agent\":\"general-purpose#1\",\"cached\":false,\"index\":1,\"parent_agent_id\":\"plan\",\"phase\":\"Read\",\"run_id\":\"wf_20260824132936_59ae80e3\",\"task\":\"read:a.txt\",\"workflow\":\"check-files\"}"
      }
    },
    {
      "kind": "tool",
      "tool": {
        "id": "call-6",
        "title": "agent general-purpose#2: read:b.txt",
        "status": "completed",
        "output": "The contents of `b.txt` are:\n\n```\nbeta\n```",
        "diffs": [],
        "locations": [],
        "timestamp": 1700000005000,
        "kind": "think",
        "argsJSON": "{\"agent\":\"general-purpose#2\",\"cached\":false,\"index\":2,\"parent_agent_id\":\"plan\",\"phase\":\"Read\",\"run_id\":\"wf_20260824132936_59ae80e3\",\"task\":\"read:b.txt\",\"workflow\":\"check-files\"}"
      }
    },
    {
      "kind": "tool",
      "tool": {
        "id": "call-7",
        "title": "[general-purpose#1] file-read {\"path\": \"/tmp/claude-1000/-home-carlo-Desktop-Spettro-Spettro-Desktop/febcdfcd-93e1-4a78-9149-1a475e52f0c7/scratchpad/l…",
        "status": "completed",
        "output": "alpha\n",
        "diffs": [],
        "locations": [
          { "path": "/tmp/claude-1000/-home-carlo-Desktop-Spettro-Spettro-Desktop/febcdfcd-93e1-4a78-9149-1a475e52f0c7/scratchpad/liveproj/a.txt" }
        ],
        "timestamp": 1700000006000,
        "kind": "read",
        "argsJSON": "{\"path\":\"/tmp/claude-1000/-home-carlo-Desktop-Spettro-Spettro-Desktop/febcdfcd-93e1-4a78-9149-1a475e52f0c7/scratchpad/liveproj/a.txt\"}"
      }
    },
    {
      "kind": "tool",
      "tool": {
        "id": "call-8",
        "title": "[general-purpose#3] file-read {\"path\": \"/tmp/claude-1000/-home-carlo-Desktop-Spettro-Spettro-Desktop/febcdfcd-93e1-4a78-9149-1a475e52f0c7/scratchpad/l…",
        "status": "completed",
        "output": "gamma\n",
        "diffs": [],
        "locations": [
          { "path": "/tmp/claude-1000/-home-carlo-Desktop-Spettro-Spettro-Desktop/febcdfcd-93e1-4a78-9149-1a475e52f0c7/scratchpad/liveproj/c.txt" }
        ],
        "timestamp": 1700000007000,
        "kind": "read",
        "argsJSON": "{\"path\":\"/tmp/claude-1000/-home-carlo-Desktop-Spettro-Spettro-Desktop/febcdfcd-93e1-4a78-9149-1a475e52f0c7/scratchpad/liveproj/c.txt\"}"
      }
    },
    {
      "kind": "tool",
      "tool": {
        "id": "call-9",
        "title": "[general-purpose#2] file-read {\"path\": \"/tmp/claude-1000/-home-carlo-Desktop-Spettro-Spettro-Desktop/febcdfcd-93e1-4a78-9149-1a475e52f0c7/scratchpad/l…",
        "status": "completed",
        "output": "beta\n",
        "diffs": [],
        "locations": [
          { "path": "/tmp/claude-1000/-home-carlo-Desktop-Spettro-Spettro-Desktop/febcdfcd-93e1-4a78-9149-1a475e52f0c7/scratchpad/liveproj/b.txt" }
        ],
        "timestamp": 1700000008000,
        "kind": "read",
        "argsJSON": "{\"path\":\"/tmp/claude-1000/-home-carlo-Desktop-Spettro-Spettro-Desktop/febcdfcd-93e1-4a78-9149-1a475e52f0c7/scratchpad/liveproj/b.txt\"}"
      }
    },
    {
      "kind": "message",
      "message": {
        "id": "msg_1",
        "role": "assistant",
        "text": "Done. The **check-files** workflow ran one phase with three parallel agents:\n\n| File | Contents |\n|------|----------|\n| `a.txt` | `alpha` |\n| `b.txt` | `beta` |\n| `c.txt` | `gamma` |\n\nThe script is saved at `.spettro/workflows/check-files.js` — you can re-run it anytime with `/workflows run check-files`.",
        "attachments": [],
        "isStreaming": false,
        "timestamp": 1700000009000
      }
    }
  ] as never
}
